### ISSUE TITLE
Doc link in the readme?

### ISSUE THREAD

**Issue by paaljoachim** [cgoldsby/LoginCritter#11]
Hey

This resource was linked in an earlier Web Designer newsletter. I am wondering about how I would go about using this especially in WordPress. It would be great to have a docs link in the readme. Thanks.

Btw I see a lot of fun with this. As hover effects to be added to the various states. Having various things going on.

**Comment by cgoldsby** [comment]
Hi @paaljoachim, this is a Swift demo for iOS applications and not compatible with any Web technologies. Thanks for your interest, though.
