### ISSUE TITLE
How to use it directly in my project?

### ISSUE THREAD

**Issue by ParthJadhav** [cgoldsby/LoginCritter#13]
I want to use it in my project and i have done it by copying your project files in my project and included a continue button in the View Controller and **I want the button to trigger a segue** when clicked but its not working, Please Help 🙂

**Comment by cgoldsby** [comment]
Sorry, adding a segue isn't really in the scope of this project. This repo was a little side idea and I, unfortunately, don't have time to work on it these days.

I appreciate your interest in this repo and hope your project goes well. Thank you. 🙇 🌻
