### ISSUE TITLE
Feature: Password strength

### ISSUE THREAD

**Issue by jfinstrom** [cgoldsby/LoginCritter#3]
Just a cool idea would be to add additional frames with frown to smile based on password strength

**Comment by ghost** [comment]
Hi @jfinstrom , @cgoldsby , Is this fixed?

**Comment by cgoldsby** [comment]
Sorry, mates this repository is just a demo. Thank you for the suggestion but I currently don't have the time to work on this. 🙇 Thank you for your interest in this little project.
